services:
  playwright:
    image: kyokley/playwright
    hostname: playwright
    build:
      context: .
      target: playwright
    depends_on:
      - mediaviewer
    volumes:
      - .:/code
    networks:
      - mediaviewer-backend
