# This file has been generated by node2nix 1.11.1. Do not edit!
{
  nodeEnv,
  fetchurl,
  fetchgit,
  nix-gitignore,
  stdenv,
  lib,
  globalBuildInputs ? [],
}: let
  sources = {
    "@popperjs/core-2.11.8" = {
      name = "_at_popperjs_slash_core";
      packageName = "@popperjs/core";
      version = "2.11.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@popperjs/core/-/core-2.11.8.tgz";
        sha512 = "P1st0aksCrn9sGZhp8GMYwBnQsbvAWsZAX44oXNNvLHGqAOcoVxmjZiohstwQ7SqKnbR47akdNi+uleWD8+g6A==";
      };
    };
    "bootstrap-5.3.8" = {
      name = "bootstrap";
      packageName = "bootstrap";
      version = "5.3.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap/-/bootstrap-5.3.8.tgz";
        sha512 = "HP1SZDqaLDPwsNiqRqi5NcP0SSXciX2s9E+RyqJIIqGo+vJeN5AJVM98CXmW/Wux0nQ5L7jeWUdplCEf0Ee+tg==";
      };
    };
    "bootstrap-icons-1.13.1" = {
      name = "bootstrap-icons";
      packageName = "bootstrap-icons";
      version = "1.13.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/bootstrap-icons/-/bootstrap-icons-1.13.1.tgz";
        sha512 = "ijombt4v6bv5CLeXvRWKy7CuM3TRTuPEuGaGKvTV5cz65rQSY8RQ2JcHt6b90cBBAC7s8fsf2EkQDldzCoXUjw==";
      };
    };
    "datatables.net-1.13.11" = {
      name = "datatables.net";
      packageName = "datatables.net";
      version = "1.13.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/datatables.net/-/datatables.net-1.13.11.tgz";
        sha512 = "AE6RkMXziRaqzPcu/pl3SJXeRa6fmXQG/fVjuRESujvkzqDCYEeKTTpPMuVJSGYJpPi32WGSphVNNY1G4nSN/g==";
      };
    };
    "datatables.net-2.3.5" = {
      name = "datatables.net";
      packageName = "datatables.net";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/datatables.net/-/datatables.net-2.3.5.tgz";
        sha512 = "Qrwc+vuw8GHo42u1usWTuriNAMW0VvLPSW3j8g3GxvatiD8wS/ZGW32VAYLLfmF4Hz0C/fo2KB3xZBfcpqqVTQ==";
      };
    };
    "datatables.net-bs5-1.13.11" = {
      name = "datatables.net-bs5";
      packageName = "datatables.net-bs5";
      version = "1.13.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/datatables.net-bs5/-/datatables.net-bs5-1.13.11.tgz";
        sha512 = "NQO15TjXo4xvZ0jReC4Uf86ezbQzPQPdaN2YncrCPhzQ6fx+2WD7DUq4ur0HbAcYHo94/M+MtD5Ch29To7Rj3Q==";
      };
    };
    "datatables.net-bs5-2.3.5" = {
      name = "datatables.net-bs5";
      packageName = "datatables.net-bs5";
      version = "2.3.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/datatables.net-bs5/-/datatables.net-bs5-2.3.5.tgz";
        sha512 = "2JA2WZz1tBxdVpYAspiqI8POdqEoAZZzqp7tISKaof2P5ufBJb+OLaahxwuB0sF9qcQh1azlU+JH1zsLBXVwXg==";
      };
    };
    "datatables.net-buttons-2.4.3" = {
      name = "datatables.net-buttons";
      packageName = "datatables.net-buttons";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/datatables.net-buttons/-/datatables.net-buttons-2.4.3.tgz";
        sha512 = "xoHD6I2kxnU/CEp97Ar0lSnAL1siucQ/5Q/otGWWfWE2VN0o4n5C2h2Ot/ZCS8kxbEHBGd873Bc2xPdJH87yOw==";
      };
    };
    "datatables.net-buttons-bs5-2.4.3" = {
      name = "datatables.net-buttons-bs5";
      packageName = "datatables.net-buttons-bs5";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/datatables.net-buttons-bs5/-/datatables.net-buttons-bs5-2.4.3.tgz";
        sha512 = "osgIyqTTXRWOF+vh19GM0ixB4kqmtQTiYmcO3v2Ca+bwUpfasI+ylEyMrHqqiON77zA+FmPTuUVHUZTJIIJWUg==";
      };
    };
    "datatables.net-scroller-2.4.3" = {
      name = "datatables.net-scroller";
      packageName = "datatables.net-scroller";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/datatables.net-scroller/-/datatables.net-scroller-2.4.3.tgz";
        sha512 = "ce6Qa7ObGQmLJYvm6eMglf54L+01/Omn3N1pw7SiQjGYv8AKRRp1ex+U0NWmx3QaWp0iEeTnBaM4G6ay4juYZg==";
      };
    };
    "datatables.net-scroller-bs5-2.4.3" = {
      name = "datatables.net-scroller-bs5";
      packageName = "datatables.net-scroller-bs5";
      version = "2.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/datatables.net-scroller-bs5/-/datatables.net-scroller-bs5-2.4.3.tgz";
        sha512 = "Dcg0dlp6XHw7MvnohbygY3fc2KxBGVPFveAlo2oXXKUTzXbiO3hWBvwnk5wKK9Bz5QP47XqqiImtui5ZprOcSg==";
      };
    };
    "jquery-3.7.1" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.7.1.tgz";
        sha512 = "m4avr8yL8kmFN8psrbFFFmB/If14iN5o9nw/NgnnM+kybDJpRsAynV2BsfpTYrTRysYUdADVD7CkUUizgkpLfg==";
      };
    };
    "jquery-migrate-3.5.2" = {
      name = "jquery-migrate";
      packageName = "jquery-migrate";
      version = "3.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery-migrate/-/jquery-migrate-3.5.2.tgz";
        sha512 = "GGvcVWK3aei2/98r7pA4UkOYvs4xVeCGvquNXADFUp9+Sr6VeOw0ktlQ9z4YlBbEFpsXBlRioAgpH/fLWinj4Q==";
      };
    };
    "jquery.shorten-1.0.0" = {
      name = "jquery.shorten";
      packageName = "jquery.shorten";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery.shorten/-/jquery.shorten-1.0.0.tgz";
        sha512 = "49rJlpcyVI/Y2eQRwSexyz6l+fwTKfurO0XttXK4XnG9eQxIuE2Fb4rwNqnsnzStJ8M7ynlhH31fWE9P70B9rg==";
      };
    };
    "slick-carousel-1.8.1" = {
      name = "slick-carousel";
      packageName = "slick-carousel";
      version = "1.8.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/slick-carousel/-/slick-carousel-1.8.1.tgz";
        sha512 = "XB9Ftrf2EEKfzoQXt3Nitrt/IPbT+f1fgqBdoxO3W/+JYvtEOW6EgxnWfr9GH6nmULv7Y2tPmEX3koxThVmebA==";
      };
    };
  };
  args = {
    name = "mediaviewer";
    packageName = "mediaviewer";
    version = "1.0.0";
    src = ./.;
    dependencies = [
      sources."@popperjs/core-2.11.8"
      sources."bootstrap-5.3.8"
      sources."bootstrap-icons-1.13.1"
      sources."datatables.net-2.3.5"
      sources."datatables.net-bs5-2.3.5"
      (sources."datatables.net-buttons-2.4.3"
        // {
          dependencies = [
            sources."datatables.net-1.13.11"
          ];
        })
      (sources."datatables.net-buttons-bs5-2.4.3"
        // {
          dependencies = [
            sources."datatables.net-1.13.11"
            sources."datatables.net-bs5-1.13.11"
          ];
        })
      sources."datatables.net-scroller-2.4.3"
      sources."datatables.net-scroller-bs5-2.4.3"
      sources."jquery-3.7.1"
      sources."jquery-migrate-3.5.2"
      sources."jquery.shorten-1.0.0"
      sources."slick-carousel-1.8.1"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Track media files";
      homepage = "https://github.com/kyokley/MediaViewer#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
in {
  args = args;
  sources = sources;
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
  nodeDependencies = nodeEnv.buildNodeDependencies (lib.overrideExisting args {
    src = stdenv.mkDerivation {
      name = args.name + "-package-json";
      src =
        nix-gitignore.gitignoreSourcePure [
          "*"
          "!package.json"
          "!package-lock.json"
        ]
        args.src;
      dontBuild = true;
      installPhase = "mkdir -p $out; cp -r ./* $out;";
    };
  });
}
