# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-11 21:12
from __future__ import unicode_literals

from django.db import migrations


def delete_posterfiles(apps, schema_editor):
    PosterFile = apps.get_model("mediaviewer", "PosterFile")
    PosterFile.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(delete_posterfiles),
    ]
