# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-12 03:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0002_auto_20161023_2108'),
        ('mediaviewer', '0002_auto_20161111_1512'),
    ]

    operations = [
    ]
