# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-17 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediaviewer", "0006_auto_20161212_0613"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usercomment",
            name="comment",
            field=models.TextField(blank=True, null=True),
        ),
    ]
