# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0007_auto_20161217_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='waiterstatus',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, db_column='datecreated'),
        ),
    ]
