# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-08 05:38
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0008_auto_20161229_0808"),
    ]

    operations = [
        migrations.AddField(
            model_name="videoprogress",
            name="file",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mediaviewer.File",
            ),
        ),
    ]
