# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-20 02:30
from __future__ import unicode_literals

from django.db import migrations

def generate_initial_mediagenre_data(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0010_mediagenre'),
    ]

    operations = [
        migrations.RunPython(generate_initial_mediagenre_data)
    ]
