# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-04 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0013_auto_20170204_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateedited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'actor',
            },
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateedited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'director',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.TextField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateedited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'genre',
            },
        ),
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('dateedited', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'writer',
            },
        ),
        migrations.RemoveField(
            model_name='posterfile',
            name='director',
        ),
        migrations.RemoveField(
            model_name='posterfile',
            name='genre',
        ),
        migrations.RemoveField(
            model_name='posterfile',
            name='writer',
        ),
        migrations.RemoveField(
            model_name='posterfile',
            name='actors',
        ),
        migrations.AddField(
            model_name='posterfile',
            name='directors',
            field=models.ManyToManyField(to='mediaviewer.Director'),
        ),
        migrations.AddField(
            model_name='posterfile',
            name='genres',
            field=models.ManyToManyField(to='mediaviewer.Genre'),
        ),
        migrations.AddField(
            model_name='posterfile',
            name='writers',
            field=models.ManyToManyField(to='mediaviewer.Writer'),
        ),
        migrations.AddField(
            model_name='posterfile',
            name='actors',
            field=models.ManyToManyField(to='mediaviewer.Actor'),
        ),
    ]
