# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-02-19 15:26
from __future__ import unicode_literals

from django.db import migrations

def regenerate_posterfiles(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0014_auto_20170204_1047'),
    ]

    operations = [
            migrations.RunPython(regenerate_posterfiles),
    ]
