# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediaviewer", "0015_auto_20170219_0926"),
    ]

    operations = [
        migrations.AddField(
            model_name="posterfile",
            name="tmdb_id",
            field=models.TextField(blank=True, null=True),
        ),
    ]
