# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-16 00:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0018_auto_20170314_2131"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersettings",
            name="binge_mode",
            field=models.BooleanField(default=True),
        ),
    ]
