# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-26 14:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mediaviewer", "0022_message_message_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="last_watched_dismissed",
        ),
        migrations.AlterField(
            model_name="usersettings",
            name="last_watched",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="mediaviewer.Path",
            ),
        ),
    ]
