# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-02 15:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mediaviewer", "0023_auto_20170826_0910"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="downloadclick",
            name="downloadtoken",
        ),
        migrations.RemoveField(
            model_name="downloadclick",
            name="user",
        ),
        migrations.DeleteModel(
            name="DownloadClick",
        ),
    ]
