# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-04 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0024_auto_20170902_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersettings',
            name='jump_to_last_watched',
            field=models.BooleanField(default=True),
        ),
    ]
