# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-12 15:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0025_usersettings_jump_to_last_watched"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersettings",
            name="auto_download",
        ),
    ]
