# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 19:43
from __future__ import unicode_literals

from django.db import migrations


def delete_posterfiles(apps, schema_editor):
    PosterFile = apps.get_model('mediaviewer', 'PosterFile')
    PosterFile.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0027_posterfile_poster_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posterfile',
            name='image',
        ),
        migrations.RunPython(delete_posterfiles),
    ]
