# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-10-24 21:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediaviewer", "0028_remove_posterfile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="posterfile",
            name="tagline",
            field=models.TextField(blank=True, null=True),
        ),
    ]
