# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-06 01:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0029_posterfile_tagline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datatransmission',
            name='datestr',
            field=models.DateField(blank=True, db_column='date'),
        ),
        migrations.AlterField(
            model_name='downloadtoken',
            name='datecreated',
            field=models.DateTimeField(blank=True, db_column='datecreated'),
        ),
        migrations.AlterField(
            model_name='downloadtoken',
            name='displayname',
            field=models.TextField(db_column='display_name'),
        ),
        migrations.AlterField(
            model_name='downloadtoken',
            name='file',
            field=models.ForeignKey(blank=True, db_column='fileid', on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.File'),
        ),
        migrations.AlterField(
            model_name='downloadtoken',
            name='filename',
            field=models.TextField(db_column='filename'),
        ),
        migrations.AlterField(
            model_name='downloadtoken',
            name='ismovie',
            field=models.BooleanField(db_column='ismovie'),
        ),
        migrations.AlterField(
            model_name='downloadtoken',
            name='path',
            field=models.TextField(db_column='path'),
        ),
        migrations.AlterField(
            model_name='downloadtoken',
            name='user',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='error',
            name='datatransmission',
            field=models.ForeignKey(blank=True, db_column='datatransmissionid', null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.DataTransmission'),
        ),
        migrations.AlterField(
            model_name='error',
            name='datecreatedstr',
            field=models.DateTimeField(blank=True, db_column='datecreated'),
        ),
        migrations.AlterField(
            model_name='error',
            name='file',
            field=models.ForeignKey(blank=True, db_column='fileid', null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.File'),
        ),
        migrations.AlterField(
            model_name='error',
            name='ignore',
            field=models.BooleanField(db_column='ignore'),
        ),
        migrations.AlterField(
            model_name='error',
            name='path',
            field=models.ForeignKey(blank=True, db_column='pathid', null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.Path'),
        ),
        migrations.AlterField(
            model_name='file',
            name='_searchString',
            field=models.TextField(blank=True, db_column='searchstr', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='datatransmission',
            field=models.ForeignKey(blank=True, db_column='datatransmissionid', null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.DataTransmission'),
        ),
        migrations.AlterField(
            model_name='file',
            name='filenamescrapeformat',
            field=models.ForeignKey(blank=True, db_column='filenamescrapeformatid', null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.FilenameScrapeFormat'),
        ),
        migrations.AlterField(
            model_name='file',
            name='hide',
            field=models.BooleanField(db_column='hide', default=False),
        ),
        migrations.AlterField(
            model_name='file',
            name='imdb_id',
            field=models.TextField(blank=True, db_column='imdb_id', null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.ForeignKey(blank=True, db_column='pathid', null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.Path'),
        ),
        migrations.AlterField(
            model_name='file',
            name='streamable',
            field=models.BooleanField(db_column='streamable', default=True),
        ),
        migrations.AlterField(
            model_name='filenamescrapeformat',
            name='episodeRegex',
            field=models.TextField(blank=True, db_column='episoderegex', null=True),
        ),
        migrations.AlterField(
            model_name='filenamescrapeformat',
            name='nameRegex',
            field=models.TextField(blank=True, db_column='nameregex', null=True),
        ),
        migrations.AlterField(
            model_name='filenamescrapeformat',
            name='seasonRegex',
            field=models.TextField(blank=True, db_column='seasonregex', null=True),
        ),
        migrations.AlterField(
            model_name='filenamescrapeformat',
            name='subPeriods',
            field=models.BooleanField(db_column='subperiods'),
        ),
        migrations.AlterField(
            model_name='filenamescrapeformat',
            name='useSearchTerm',
            field=models.BooleanField(db_column='usesearchterm'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='datecreated',
            field=models.DateTimeField(db_column='datecreated'),
        ),
        migrations.AlterField(
            model_name='loginevent',
            name='user',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, db_column='body'),
        ),
        migrations.AlterField(
            model_name='message',
            name='datecreated',
            field=models.DateTimeField(db_column='datecreated'),
        ),
        migrations.AlterField(
            model_name='message',
            name='level',
            field=models.IntegerField(db_column='level'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(blank=True, choices=[('regular', 'Regular'), ('last_watched', 'Last Watched')], default='regular', max_length=15),
        ),
        migrations.AlterField(
            model_name='message',
            name='sent',
            field=models.BooleanField(db_column='sent'),
        ),
        migrations.AlterField(
            model_name='message',
            name='touser',
            field=models.ForeignKey(db_column='touserid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='path',
            name='defaultScraper',
            field=models.ForeignKey(blank=True, db_column='defaultscraperid', null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.FilenameScrapeFormat'),
        ),
        migrations.AlterField(
            model_name='path',
            name='is_movie',
            field=models.BooleanField(db_column='ismovie'),
        ),
        migrations.AlterField(
            model_name='path',
            name='lastCreatedFileDate',
            field=models.DateTimeField(blank=True, db_column='lastcreatedfiledate', null=True),
        ),
        migrations.AlterField(
            model_name='path',
            name='override_display_name',
            field=models.TextField(blank=True, db_column='display_name', null=True),
        ),
        migrations.AlterField(
            model_name='posterfile',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, db_column='datecreated'),
        ),
        migrations.AlterField(
            model_name='posterfile',
            name='dateedited',
            field=models.DateTimeField(auto_now=True, db_column='dateedited'),
        ),
        migrations.AlterField(
            model_name='posterfile',
            name='file',
            field=models.ForeignKey(blank=True, db_column='fileid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_posterfile', to='mediaviewer.File'),
        ),
        migrations.AlterField(
            model_name='posterfile',
            name='path',
            field=models.ForeignKey(blank=True, db_column='pathid', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='_posterfile', to='mediaviewer.Path'),
        ),
        migrations.AlterField(
            model_name='request',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, db_column='datecreated'),
        ),
        migrations.AlterField(
            model_name='request',
            name='dateedited',
            field=models.DateTimeField(auto_now=True, db_column='dateedited'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='requestvote',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, db_column='datecreated'),
        ),
        migrations.AlterField(
            model_name='requestvote',
            name='request',
            field=models.ForeignKey(db_column='requestid', null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.Request'),
        ),
        migrations.AlterField(
            model_name='requestvote',
            name='user',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='sitegreeting',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, db_column='datecreated'),
        ),
        migrations.AlterField(
            model_name='sitegreeting',
            name='greeting',
            field=models.TextField(blank=True, db_column='greeting'),
        ),
        migrations.AlterField(
            model_name='sitegreeting',
            name='user',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, db_column='datecreated'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='dateedited',
            field=models.DateTimeField(auto_now=True, db_column='dateedited'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='file',
            field=models.ForeignKey(db_column='fileid', on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.File'),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='user',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='usercomment',
            name='viewed',
            field=models.BooleanField(db_column='viewed'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='can_download',
            field=models.BooleanField(db_column='can_download'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='can_login',
            field=models.BooleanField(db_column='can_login', default=True),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='datecreated',
            field=models.DateTimeField(blank=True, db_column='datecreated'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='dateedited',
            field=models.DateTimeField(blank=True, db_column='dateedited'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='default_sort',
            field=models.TextField(db_column='default_sort'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='force_password_change',
            field=models.BooleanField(db_column='force_password_change', default=False),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='ip_format',
            field=models.TextField(db_column='ip_format'),
        ),
        migrations.AlterField(
            model_name='usersettings',
            name='user',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='filename',
            field=models.TextField(db_column='filename', null=True),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='hashed_filename',
            field=models.TextField(db_column='hashedfilename'),
        ),
        migrations.AlterField(
            model_name='videoprogress',
            name='user',
            field=models.ForeignKey(db_column='userid', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waiterstatus',
            name='datecreated',
            field=models.DateTimeField(auto_now_add=True, db_column='datecreated'),
        ),
        migrations.AlterField(
            model_name='waiterstatus',
            name='failureReason',
            field=models.TextField(db_column='failurereason'),
        ),
        migrations.AlterField(
            model_name='waiterstatus',
            name='status',
            field=models.BooleanField(db_column='status'),
        ),
    ]
