# Generated by Django 2.1.5 on 2019-01-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediaviewer", "0030_auto_20190105_1925"),
    ]

    operations = [
        migrations.AlterField(
            model_name="file",
            name="finished",
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name="file",
            name="skip",
            field=models.BooleanField(blank=True),
        ),
        migrations.AlterField(
            model_name="filenamescrapeformat",
            name="subPeriods",
            field=models.BooleanField(blank=True, db_column="subperiods"),
        ),
        migrations.AlterField(
            model_name="filenamescrapeformat",
            name="useSearchTerm",
            field=models.BooleanField(blank=True, db_column="usesearchterm"),
        ),
        migrations.AlterField(
            model_name="path",
            name="skip",
            field=models.BooleanField(blank=True),
        ),
    ]
