# Generated by Django 2.1.5 on 2019-05-27 14:25

import re
from django.db import migrations

HOME_DIR_REGEX = re.compile(r"^/home/yokley/")


def remove_home_dir(apps, schema_editor):
    Path = apps.get_model("mediaviewer", "Path")
    paths = Path.objects.all()

    for path in paths:
        match = HOME_DIR_REGEX.search(path.localpathstr)
        if not match:
            continue

        end = match.end()
        new_path = path.localpathstr[end:]
        path.localpathstr = new_path
        path.save()


class Migration(migrations.Migration):

    dependencies = [
        ("mediaviewer", "0033_auto_20190302_2010"),
    ]

    operations = [
        migrations.RunPython(remove_home_dir),
    ]
