# Generated by Django 2.2.13 on 2020-10-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediaviewer", "0035_path_finished"),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationSite",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site_name", models.TextField()),
                ("url", models.URLField()),
            ],
        ),
    ]
