# Generated by Django 2.2.25 on 2022-01-01 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0040_auto_20211224_0942"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="error",
            name="datatransmission",
        ),
        migrations.RemoveField(
            model_name="file",
            name="datatransmission",
        ),
        migrations.DeleteModel(
            name="DataTransmission",
        ),
    ]
