# Generated by Django 3.2.16 on 2023-01-02 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0042_auto_20220319_1515"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="last_watched",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="mediaviewer.path",
            ),
        ),
    ]
