# Generated by Django 3.2.20 on 2023-07-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0043_alter_usersettings_last_watched'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='display_name',
            field=models.TextField(blank=True, default='', editable=False),
        ),
    ]
