# Generated by Django 3.2.20 on 2023-08-07 15:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0044_usersettings_allow_password_logins"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sitegreeting",
            name="user",
        ),
    ]
