# Generated by Django 3.2.20 on 2023-08-10 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0046_file__display_name'),
    ]

    operations = [
    ]
