# Generated by Django 3.2.20 on 2023-09-08 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0047_usersettings_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('plot', models.TextField(blank=True, default='')),
                ('extendedplot', models.TextField(blank=True, default='')),
                ('episodename', models.CharField(blank=True, default='', max_length=100)),
                ('rated', models.CharField(blank=True, default='', max_length=100)),
                ('rating', models.CharField(blank=True, default='', max_length=32)),
                ('tmdb', models.CharField(blank=True, default='', max_length=32)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('tagline', models.CharField(blank=True, default='', max_length=100)),
                ('actors', models.ManyToManyField(blank=True, to='mediaviewer.Actor')),
                ('directors', models.ManyToManyField(blank=True, to='mediaviewer.Director')),
                ('genres', models.ManyToManyField(blank=True, to='mediaviewer.Genre')),
                ('writers', models.ManyToManyField(blank=True, to='mediaviewer.Writer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('finished', models.BooleanField(default=False)),
                ('search_terms', models.CharField(blank=True, default='', max_length=256)),
                ('override_display_name', models.CharField(blank=True, default='', max_length=256)),
                ('imdb', models.CharField(blank=True, default='', max_length=64)),
                ('tvdb', models.CharField(blank=True, default='', max_length=64)),
                ('poster', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tv', to='mediaviewer.poster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('finished', models.BooleanField(default=False)),
                ('search_terms', models.CharField(blank=True, default='', max_length=256)),
                ('override_display_name', models.CharField(blank=True, default='', max_length=256)),
                ('imdb', models.CharField(blank=True, default='', max_length=64)),
                ('poster', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='mediaviewer.poster')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('_path', models.CharField(blank=True, max_length=256)),
                ('skip', models.BooleanField(blank=True, default=False)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.movie')),
                ('tv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.tv')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=256)),
                ('override_display_name', models.CharField(blank=True, default='', max_length=256)),
                ('override_season', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('override_episode', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('skip', models.BooleanField(blank=True, default=False)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('media_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.mediapath')),
                ('poster', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediaviewer.poster')),
                ('scraper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediaviewer.filenamescrapeformat')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
