# Generated by Django 3.2.20 on 2023-09-29 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mediaviewer.models.core


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mediaviewer', '0047_usersettings_theme'),
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('plot', models.TextField(blank=True, default='')),
                ('extendedplot', models.TextField(blank=True, default='')),
                ('episodename', models.CharField(blank=True, default='', max_length=100)),
                ('rated', models.CharField(blank=True, default='', max_length=100)),
                ('rating', models.CharField(blank=True, default='', max_length=32)),
                ('tmdb', models.CharField(blank=True, default='', max_length=32)),
                ('imdb', models.CharField(blank=True, default='', max_length=32)),
                ('image', models.ImageField(upload_to='uploads/%Y/%m/%d/')),
                ('tagline', models.CharField(blank=True, default='', max_length=100)),
                ('actors', models.ManyToManyField(blank=True, to='mediaviewer.Actor')),
                ('directors', models.ManyToManyField(blank=True, to='mediaviewer.Director')),
                ('genres', models.ManyToManyField(blank=True, to='mediaviewer.Genre')),
                ('writers', models.ManyToManyField(blank=True, to='mediaviewer.Writer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='downloadtoken',
            name='datecreated',
        ),
        migrations.RemoveField(
            model_name='downloadtoken',
            name='file',
        ),
        migrations.RemoveField(
            model_name='downloadtoken',
            name='ismovie',
        ),
        migrations.RemoveField(
            model_name='usersettings',
            name='last_watched',
        ),
        migrations.RemoveField(
            model_name='videoprogress',
            name='file',
        ),
        migrations.AddField(
            model_name='downloadtoken',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='TV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('finished', models.BooleanField(default=False)),
                ('_search_terms', models.CharField(blank=True, default='', max_length=256)),
                ('poster', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tv', to='mediaviewer.poster')),
            ],
            options={
                'verbose_name_plural': 'TV',
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('finished', models.BooleanField(default=False)),
                ('_search_terms', models.CharField(blank=True, default='', max_length=256)),
                ('poster', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movie', to='mediaviewer.poster')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, mediaviewer.models.core.ViewableObjectMixin),
        ),
        migrations.CreateModel(
            name='MediaPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('_path', models.CharField(blank=True, max_length=256)),
                ('skip', models.BooleanField(blank=True, default=False)),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.movie')),
                ('tv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.tv')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=256)),
                ('display_name', models.CharField(max_length=256)),
                ('season', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('episode', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('hide', models.BooleanField(blank=True, default=False)),
                ('size', models.BigIntegerField(blank=True, null=True)),
                ('media_path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.mediapath')),
                ('poster', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='media_file', to='mediaviewer.poster')),
                ('scraper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediaviewer.filenamescrapeformat')),
            ],
            options={
                'abstract': False,
            },
            bases=(models.Model, mediaviewer.models.core.ViewableObjectMixin),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_edited', models.DateTimeField(auto_now=True)),
                ('viewed', models.BooleanField(default=False)),
                ('media_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mediaviewer.mediafile')),
                ('movie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='mediaviewer.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='downloadtoken',
            name='media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.mediafile'),
        ),
        migrations.AddField(
            model_name='downloadtoken',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.movie'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='last_watched_movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediaviewer.movie'),
        ),
        migrations.AddField(
            model_name='usersettings',
            name='last_watched_tv',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediaviewer.tv'),
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='media_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.mediafile'),
        ),
        migrations.AddField(
            model_name='videoprogress',
            name='movie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mediaviewer.movie'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('user', 'media_file'), name='unique_user_media_file'),
        ),
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.UniqueConstraint(fields=('user', 'movie'), name='unique_user_movie'),
        ),
    ]
