# Generated by Django 3.2.20 on 2023-09-08 18:16

from pathlib import Path as Pathlib
import re
from django.db import migrations


yearRegex = re.compile(r"20\d{2}\D?.*$")
dvdRegex = re.compile(r"[A-Z]{2,}.*$")
formatRegex = re.compile(r"\b(xvid|avi|XVID|AVI)+\b")
punctuationRegex = re.compile(r"[^a-zA-Z0-9]+")


def path_display_name(obj):
    return obj.override_display_name or path_short_name(obj).replace(".", " ").title()


def path_short_name(obj):
    return obj.localpathstr.rpartition("/")[-1]


def file_display_name(obj):
    pass


def file_raw_search_string(obj):
    searchStr = (
        obj.override_filename
        or obj._searchString
        or get_search_term(obj)
    )
    return searchStr


def get_search_term(obj):
    if obj.path.is_movie:
        searchTerm = obj.filename
    else:
        searchTerm = obj.path.localpathstr.rpartition("/")[-1]
    searchTerm = yearRegex.sub("", searchTerm)
    searchTerm = dvdRegex.sub("", searchTerm)
    searchTerm = formatRegex.sub("", searchTerm)
    searchTerm = punctuationRegex.sub(" ", searchTerm)
    searchTerm = searchTerm.strip()

    return searchTerm


def file_short_name(obj):
    if obj.override_filename:
        return obj.override_filename

    if (obj.filenamescrapeformat is None or obj.filenamescrapeformat.useSearchTerm):
        name = file_raw_search_string(obj)
    else:
        nameRegex = re.compile(obj.filenamescrapeformat.nameRegex).findall(
            obj.filename
        )
        name = nameRegex and nameRegex[0] or None
    return (
        name
        and (
            obj.filenamescrapeformat and obj.filenamescrapeformat.subPeriods
            and name.replace(".", " ").replace("-", " ").title()
            or name
        ).strip()
        or obj.filename
    )


def forward(apps, schema_editor):
    TV = apps.get_model('mediaviewer', 'TV')
    Movie = apps.get_model('mediaviewer', 'Movie')
    Path = apps.get_model('mediaviewer', 'Path')
    File = apps.get_model('mediaviewer', 'File')
    MediaPath = apps.get_model('mediaviewer', 'MediaPath')
    MediaFile = apps.get_model('mediaviewer', 'MediaFile')

    tv_path_qs = Path.objects.filter(is_movie=False)

    for path in tv_path_qs:
        obj, created = TV.objects.get_or_create(name=path_display_name(path),
                                                defaults=dict(finished=path.finished,
                                                              imdb=path.imdb_id or '',
                                                              tvdb=path.tvdb_id or '',
                                                              )
                                                )
        mp = MediaPath.objects.create(_path=path.localpathstr,
                                      skip=path.skip,
                                      tv=obj)

        for file in path.file_set.all():
            MediaFile.objects.create(media_path=mp,
                                     filename=file.filename,
                                     override_display_name=file.override_filename,
                                     override_season=int(file.override_season) if file.override_season is not None and file.override_season != '' else None,
                                     override_episode=int(file.override_episode) if file.override_episode is not None and file.override_episode != '' else None,
                                     scraper=file.filenamescrapeformat,
                                     skip=file.skip,
                                     size=file.size,
                                     )

    movie_file_qs = File.objects.filter(path__is_movie=True).select_related('path', 'filenamescrapeformat')

    for movie_file in movie_file_qs:
        imdb = movie_file.imdb_id if movie_file.imdb_id and movie_file.imdb_id.lower() != 'none' else ''
        movie = Movie.objects.create(name=file_short_name(movie_file),
                                     finished=movie_file.finished,
                                     imdb=imdb,
                                     )

        path = Pathlib(movie_file.path.localpathstr) / movie_file.filename
        mp = MediaPath.objects.create(_path=str(path),
                                      skip=movie_file.skip,
                                      movie=movie)

        MediaFile.objects.create(media_path=mp,
                                 filename=movie_file.filename,
                                 override_display_name=movie_file.override_filename,
                                 scraper=movie_file.filenamescrapeformat,
                                 skip=movie_file.skip,
                                 size=movie_file.size,
                                 )


class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0048_mediafile_mediapath_movie_poster_tv'),
    ]

    operations = [
        migrations.RunPython(forward)
    ]
