# Generated by Django 3.2.20 on 2023-10-29 12:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0049_refactor"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Error",
        ),
    ]
