# Generated by Django 3.2.20 on 2023-11-04 13:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0050_delete_error"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="path",
            name="defaultScraper",
        ),
        migrations.RemoveField(
            model_name="posterfile",
            name="actors",
        ),
        migrations.RemoveField(
            model_name="posterfile",
            name="directors",
        ),
        migrations.RemoveField(
            model_name="posterfile",
            name="file",
        ),
        migrations.RemoveField(
            model_name="posterfile",
            name="genres",
        ),
        migrations.RemoveField(
            model_name="posterfile",
            name="path",
        ),
        migrations.RemoveField(
            model_name="posterfile",
            name="writers",
        ),
        migrations.RemoveField(
            model_name="usercomment",
            name="file",
        ),
        migrations.RemoveField(
            model_name="usercomment",
            name="user",
        ),
        migrations.DeleteModel(
            name="File",
        ),
        migrations.DeleteModel(
            name="Path",
        ),
        migrations.DeleteModel(
            name="PosterFile",
        ),
        migrations.DeleteModel(
            name="UserComment",
        ),
    ]
