# Generated by Django 3.2.20 on 2023-11-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0052_auto_20231104_2316"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="hide",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="tv",
            name="hide",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="mediapath",
            name="_path",
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
    ]
