# Generated by Django 3.2.25 on 2024-03-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0054_auto_20231204_2013"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="episodename",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="poster",
            name="rated",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
        migrations.AlterField(
            model_name="poster",
            name="tagline",
            field=models.CharField(blank=True, default="", max_length=256),
        ),
    ]
