# Generated by Django 3.2.25 on 2024-05-12 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0059_alter_mediapath__path'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='collections',
            field=models.ManyToManyField(to='mediaviewer.Collection'),
        ),
        migrations.AddField(
            model_name='tv',
            name='collections',
            field=models.ManyToManyField(to='mediaviewer.Collection'),
        ),
    ]
