# Generated by Django 3.2.25 on 2024-05-25 04:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0061_auto_20240521_0825"),
    ]

    operations = [
        migrations.AlterField(
            model_name="poster",
            name="image",
            field=models.ImageField(blank=True, upload_to="uploads/%Y/%m/%d/"),
        ),
    ]
