# Generated by Django 3.2.25 on 2024-06-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mediaviewer', '0062_alter_poster_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
