# Generated by Django 4.2.16 on 2024-11-30 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediaviewer", "0064_remove_usersettings_ip_format"),
    ]

    operations = [
        migrations.AddField(
            model_name="tv",
            name="recommendations",
            field=models.ManyToManyField(to="mediaviewer.tv"),
        ),
    ]
