# Generated by Django 4.2.18 on 2025-05-29 12:56

from django.db import migrations


def enable_password_logins(apps, schema_editor):
    UserSettings = apps.get_model("mediaviewer", "UserSettings")
    UserSettings.objects.all().update(allow_password_logins=True)


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0064_remove_usersettings_ip_format"),
    ]

    operations = [migrations.RunPython(enable_password_logins)]
