# Generated by Django 5.2.5 on 2025-10-16 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0065_enable_password_logins"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersettings",
            name="allow_password_logins",
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
