# Generated by Django 4.2.16 on 2024-11-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mediaviewer", "0065_tv_recommendations"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="recommendations",
            field=models.ManyToManyField(to="mediaviewer.movie"),
        ),
    ]
