# Generated by Django 5.2.5 on 2026-03-20

from collections import defaultdict

from django.db import migrations

ABSOLUTE_PREFIX = "/home/yokley/"


def remove_absolute_paths_from_mediapath(apps, schema_editor):
    MediaPath = apps.get_model("mediaviewer", "MediaPath")

    candidates = list(
        MediaPath.objects.filter(_path__startswith=ABSOLUTE_PREFIX)
        .only("id", "_path")
        .order_by("id")
    )

    if not candidates:
        return

    normalized_by_id = {
        mp.id: mp._path[len(ABSOLUTE_PREFIX) :] for mp in candidates
    }

    conflicting_ids_by_path = defaultdict(set)

    for mp_id, normalized_path in normalized_by_id.items():
        conflicting_ids_by_path[normalized_path].add(mp_id)

    existing_normalized_rows = MediaPath.objects.filter(
        _path__in=set(normalized_by_id.values())
    ).values_list("id", "_path")

    for existing_id, existing_path in existing_normalized_rows:
        if (
            existing_path in conflicting_ids_by_path
            and existing_id not in conflicting_ids_by_path[existing_path]
        ):
            conflicting_ids_by_path[existing_path].add(existing_id)

    collisions = {
        path: sorted(ids)
        for path, ids in conflicting_ids_by_path.items()
        if len(ids) > 1
    }
    if collisions:
        preview = ", ".join(
            [f"{path!r}: ids={ids}" for path, ids in list(collisions.items())[:10]]
        )
        raise RuntimeError(
            "Cannot normalize mediapath _path values due to unique collisions. "
            f"Conflicts (first 10): {preview}"
        )

    for mp in candidates:
        mp._path = normalized_by_id[mp.id]
        mp.save(update_fields=["_path"])


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0066_alter_usersettings_allow_password_logins"),
    ]

    operations = [
        migrations.RunPython(
            remove_absolute_paths_from_mediapath,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
