# Generated by Django 6.0.6 on 2026-06-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0067_apikey"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadtoken",
            name="is_mcp",
            field=models.BooleanField(default=False),
        ),
    ]
