# Generated by Django 6.0.6 on 2026-06-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0068_downloadtoken_is_mcp"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadtoken",
            name="og_image",
            field=models.TextField(blank=True, db_column="og_image", default=""),
        ),
        migrations.AddField(
            model_name="downloadtoken",
            name="og_title",
            field=models.TextField(blank=True, db_column="og_title", default=""),
        ),
        migrations.AddField(
            model_name="downloadtoken",
            name="og_type",
            field=models.TextField(blank=True, db_column="og_type", default=""),
        ),
        migrations.AddField(
            model_name="downloadtoken",
            name="og_url",
            field=models.TextField(blank=True, db_column="og_url", default=""),
        ),
    ]
