# Generated by Django 6.1 on 2026-08-28 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0069_downloadtoken_og_image_downloadtoken_og_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediapath",
            name="filename",
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name="mediapath",
            name="_path",
            field=models.CharField(
                blank=True, db_index=True, max_length=1024, unique=True
            ),
        ),
    ]
