# Generated by Django 6.1 on 2026-08-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("mediaviewer", "0070_mediapath_filename_alter_mediapath__path"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="subtitle_files",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AddField(
            model_name="mediapath",
            name="subtitle_files",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
