name: Docker Image CI

on:
  push:
    branches: [ main ]

jobs:
  publish:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dagger
        run: pip install -r dagger-requirements.txt

      - name: Run Dagger pipeline
        env:
          DOCKER_USER: ${{secrets.DOCKER_USER}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
        run: make ci
